Player indicator
KevinHuang78759/TempoRary pull request #39
Opened 2023-05-01 13:45 UTC by Melanie-Gao

## Summary

2023-05-01 21:00 UTC, mluo24 requested changes
I think the movement of the particles is a bit too extreme and they shouldn't be lasting this long. Also fix the rest of the changes I commented on and we can merge it.

2023-05-01 21:00 UTC, mluo24 commented on core/src/edu/cornell/gdiac/temporary/GameCanvas.java
Can you get rid of these changes in GameCanvas?

2023-05-01 21:00 UTC, mluo24 commented on core/src/edu/cornell/gdiac/temporary/GameplayController.java
> +		s.setTexture(missIndicator);
These can all be merged into a singular method

2023-05-01 21:00 UTC, mluo24 commented on core/src/edu/cornell/gdiac/temporary/GameplayController.java
> +		}
remove print

2023-05-01 21:00 UTC, mluo24 commented on core/src/edu/cornell/gdiac/temporary/GameplayController.java
> +
It doesn't seem like this is complete

2023-05-02 15:01 UTC, Melanie-Gao commented on core/src/edu/cornell/gdiac/temporary/GameplayController.java
> +
The commented-out code is when we want multiple indicators to appear at the same time. The current implementation garbage collects everything so that only one indicator appears at a time.

2023-05-02 15:04 UTC, Melanie-Gao commented
Made the changes!

2023-05-05 22:30 UTC, mluo24 reviewed
Velocity is still too high and age maybe a bit too high. The movement needs to be subtle because I think right now it's kind of a lot.

Please also add the "ok" category.

Also, when you're done, I recommend sending a video to the discord so marya can also take a look at it.

2023-05-09 01:32 UTC, mluo24 approved these changes
I think we should fix garbage collection for this in the next sprint

2023-05-09 02:23 UTC, merged