Melanie/level-select-animation
KevinHuang78759/TempoRary pull request #60
Opened 2023-05-13 17:14 UTC by Melanie-Gao

created animation for level select.
changed coordinates to be relative.

2023-05-13 18:58 UTC, mluo24 requested changes
Thanks Melanie for making these changes! The animation looks pretty good! I will leave my changes here that I think are necessary:

1. The animation needs to be much quicker. like the transfer should happen in 1 second.
2. You need to disable button clicks while the transition is happening because when you spam click, you get weird looking things happening (should be an if statement in the update)
3. Thanks for using relative coordinates, but it doesn't seem like you adjust for when the screen size actually changes. If you full screen, everything is still the same width apart, but as if you were in the old screen size. Size and total position of all the elements also needs to change (see image below).
4. Having the far albums smoothly transform would be nice because right now, they abruptly disappear. A transform from right to left off screen or left to right off screen would be nice, but if you cannot get it done by the end of today, leave it.
5. The arrow button locations are kind of odd. I would just use a square/rectangle with width and height to check for distances.

<img width="1512" alt="image" src="https://github.com/KevinHuang78759/TempoRary/assets/69130822/ef7b9aca-2c3a-4975-a480-10ae370f3127">

2023-05-13 19:16 UTC, Melanie-Gao commented
Thanks, Miranda! 1 & 2 are fixed, and I'm working on the rest right now.

2023-05-14 06:05 UTC, mluo24 commented
> Thanks, Miranda! 1 & 2 are fixed, and I'm working on the rest right now.

Thanks Melanie! It should still be a smidge faster. Nice job on the button disabling though!

I would prioritize #3 and #5, where #5 should not take too long, but #4 may require more specification.

2023-05-14 21:26 UTC, mluo24 approved these changes
Thank you again for working on this! I'm going to approve it rn because you're pretty much done, but these are the few things I definitely need you to do before you merge:

1. Your scales are slightly off when you resize because I think you multiply by scales twice (see my inline comments)
2. You need to get rid of all your Vector2 initializations because you initialize way too many for it to be efficient. Either limit it to like <5 initializations throughout the whole program lifecycle or get rid of them entirely. I would look at Kevin's code for more inspiration, or look at my MenuMode but I also have very few elements there to place.

2023-05-14 21:26 UTC, mluo24 commented on core/src/edu/cornell/gdiac/temporary/LevelSelect.java
> +        hardButtonCoords = new Vector2((width/2f)+(width/10f), height/4f);
do not initialize Vector2 coordinates anymore, and this is even worse since I think every time you resize the screen, it initializes new coordinates.

2023-05-14 21:26 UTC, mluo24 commented on core/src/edu/cornell/gdiac/temporary/LevelSelect.java
> +                albumScales[selectedLevel]*scale);
I think you have an additional scale multiplication here that is unnecessary because you set the scales in `albumScales`.

2023-05-14 21:26 UTC, mluo24 commented on core/src/edu/cornell/gdiac/temporary/LevelSelect.java
> +
redundant?

2023-05-15 15:04 UTC, merged